initialize_plan:
	terraform plan --target=google_artifact_registry_repository.sakamomo_family_api --target=google_project_service.gcp_service_apis

initialize_apply:
	terraform apply --target=google_artifact_registry_repository.sakamomo_family_api --target=google_project_service.gcp_service_apis
